# Generated by Django 4.1 on 2023-07-16 03:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracionpaginas",
            name="estado_paginas_empresas",
            field=models.BooleanField(default=True),
        ),
    ]
